name: East Coast Family Reunion
favicon: null
layout_spectrum: 1
typography_spectrum: 0.25911
title: East Coast Family Reunion
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2c6ccf'
    - '#7cc1fa'
    - '#00000c'
    - '#d9a973'
    - '#7b6c2e'
  brandStrength: 0.125
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
