name: East Coast Family Reunion
favicon: null
layout_spectrum: 0.17828711844049394
typography_spectrum: 0.5525264728348702
title: East Coast Family Reunion
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2c6ccf'
    - '#7cc1fa'
    - '#00000c'
    - '#d9a973'
    - '#7b6c2e'
  brandStrength: 0.998209856916219
  lightness: 0.6883218488655984
  saturation: 0.48076067212969065
  rhythmicContrast: 0.2681355809327215
purpose: []
